server:
  port: 8011

management:
  security:
    enabled: false   
spring:
  application:
    name: lottery

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://admin:admin123@127.0.0.1:8761/eureka/
#  instance:
#    prefer-ip-address: true

logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: INFO
    #org.springframework.web.servlet.DispatcherServlet: DEBUG

